In [1]:
import numpy as np
import cv2
from tensorflow.keras.models import load_model
from PIL import Image
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.imagenet_utils import preprocess_input

cap = cv2.VideoCapture(0)

while True:
    
    _, img = cap.read()
    
    model = load_model(r'F:\MACHINE_LEARNING\CUSTOM_OBJECT_DETECTION\mobile_pen.h5')
    #img = cv2.imread(r"C:\Users\prash\Desktop\data\cotton plant leaf disease\train2\diseased cotton leaf\dis_leaf (31)_iaip.jpg")
    img1 = img.copy()
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (224,224))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis=0)
    img = preprocess_input(img)
    pred = np.argmax(model.predict(img))
    print(pred)
    
    
    img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
    img1 = cv2.resize(img1, (224,224))
    lower = np.array([60,60,60])
    higher = np.array([250,250,250])
    mask = cv2.inRange(img1, lower, higher)
    cnt,_ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    cnt_img = cv2.drawContours(img1, cnt, -1,255,3)
    c = max(cnt, key = cv2.contourArea)
    x,y,w,h = cv2.boundingRect(c)
    
    if (pred == [0]):
        name = "Diseased cotton leaf"
        cv2.rectangle(img1, (x,y),(x+w, y+h),(255,0,0),2)
        cv2.putText(img1, name, (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))
    elif (pred == [1]):
        name = "Diseased cotton plant"
        cv2.rectangle(img1, (20,20),(210, 210),(255,0,0),2)
        cv2.putText(img1, name, (17,17), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))
    elif (pred == [2]):
        name = "Fresh cotton leaf"
        cv2.rectangle(img1, (20,20),(210, 210),(255,0,0),2)
        cv2.putText(img1, name, (17,17), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))
    else:
        name = "Fresh cotton plant"
        cv2.rectangle(img1, (20,20),(210, 210),(255,0,0),2)
        cv2.putText(img1, name, (17,17), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))
    
    
    cv2.imshow("Video", img1)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

2
2
0
0
0
2
0
2
0
0
2
2
2
2
2
0
2
2
2
2
0
2
0
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
0
2
2
2
0
2
2
2
2
2
0
0
0
0
0
0
2
2
0
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
0


In [5]:
import numpy as np
import cv2
from tensorflow.keras.models import load_model
from PIL import Image
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.imagenet_utils import preprocess_input

cap = cv2.VideoCapture(0)

while True:
    
    _, img = cap.read()
    
    model = load_model(r'F:\MACHINE_LEARNING\CUSTOM_OBJECT_DETECTION\mobile_pen.h5')
    img = cv2.imread(r"F:\MACHINE_LEARNING\CUSTOM_OBJECT_DETECTION\train\Pen\pen 1.jpg")
    img1 = img.copy()
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (224,224))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis=0)
    img = preprocess_input(img)
    pred = np.argmax(model.predict(img))
    print(pred)
    
    
    img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
    img1 = cv2.resize(img1, (224,224))
    #lower = np.array([120,120,120])
    #higher = np.array([250,250,250])
    #mask = cv2.inRange(img1, lower, higher)
    #cnt,_ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    #cnt_img = cv2.drawContours(img1, cnt, -1,255,3)
    #c = max(cnt, key = cv2.contourArea)
    #x,y,w,h = cv2.boundingRect(c)
    
    if (pred == [0]):
        name = "Mobile"
        cv2.rectangle(img1, (20,20),(210, 210),(255,0,0),2)
        cv2.putText(img1, name, (17,17), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))
    else:
        name = "Pen"
        cv2.rectangle(img1, (20,20),(210, 210),(255,0,0),2)
        cv2.putText(img1, name, (17,17), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))
    
    
    cv2.imshow("Video", img1)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


# WebCam

In [1]:
import numpy as np
import cv2
from tensorflow.keras.models import load_model
from PIL import Image
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.imagenet_utils import preprocess_input

cap = cv2.VideoCapture(0)

while True:

    _, img = cap.read()

    model = load_model(r'F:\MACHINE_LEARNING\CUSTOM_OBJECT_DETECTION\mobile_pen.h5')
    #img = cv2.imread(r"F:\MACHINE_LEARNING\CUSTOM_OBJECT_DETECTION\train\Pen\pen 1.jpg")
    img1 = img.copy()
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (224,224))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis=0)
    img = preprocess_input(img)
    pred = np.argmax(model.predict(img))
    #print(pred)


    img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
    img1 = cv2.resize(img1, (224,224))
    '''lower = np.array([120,120,120])
    higher = np.array([250,250,250])
    mask = cv2.inRange(img1, lower, higher)
    cnt,_ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    cnt_img = cv2.drawContours(img1, cnt, -1,255,3)
    c = max(cnt, key = cv2.contourArea)
    x,y,w,h = cv2.boundingRect(c)'''

    if (pred == [0]):
        name = "Mobile"
        cv2.rectangle(img1, (20,20),(210, 210),(255,0,0),2)
        cv2.putText(img1, name, (20,20), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))
    else:
        name = "Pen"
        cv2.rectangle(img1, (20,20),(210, 210),(255,0,0),2)
        cv2.putText(img1, name, (20,20), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))


    cv2.imshow("Video", img1)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

# Image

In [3]:
import numpy as np
import cv2
from tensorflow.keras.models import load_model
from PIL import Image
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.imagenet_utils import preprocess_input

#cap = cv2.VideoCapture(0)

#while True:

#_, img = cap.read()

model = load_model(r'F:\MACHINE_LEARNING\CUSTOM_OBJECT_DETECTION\mobile_pen.h5')
img = cv2.imread(r"F:\MACHINE_LEARNING\CUSTOM_OBJECT_DETECTION\train\Mobile\mobile 10.jpg")
img1 = img.copy()
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = cv2.resize(img, (224,224))
img = image.img_to_array(img)
img = np.expand_dims(img, axis=0)
img = preprocess_input(img)
pred = np.argmax(model.predict(img))
#print(pred)


img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
img1 = cv2.resize(img1, (224,224))
'''lower = np.array([120,120,120])
higher = np.array([250,250,250])
mask = cv2.inRange(img1, lower, higher)
cnt,_ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
cnt_img = cv2.drawContours(img1, cnt, -1,255,3)
c = max(cnt, key = cv2.contourArea)
x,y,w,h = cv2.boundingRect(c)'''

if (pred == [0]):
    name = "Mobile"
    cv2.rectangle(img1, (20,20),(210, 210),(255,0,0),2)
    cv2.putText(img1, name, (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))
else:
    name = "Pen"
    cv2.rectangle(img1, (20,20),(210, 210),(255,0,0),2)
    cv2.putText(img1, name, (20,20), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))


cv2.imshow("Video", img1)
    
cv2.waitKey(0)
cv2.destroyAllWindows()

AttributeError: 'NoneType' object has no attribute 'copy'

In [23]:
import numpy as np
import cv2

cap = cv2.VideoCapture(0)

classifier = cv2.CascadeClassifier(r'F:\MACHINE_LEARNING\CUSTOM_OBJECT_DETECTION\train\classifier/cascade.xml')

while True:

    _, img = cap.read()

    img = cv2.resize(img,(32,32))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = classifier.detectMultiScale(img, 1.0485258, 6)

    if (pred == [0]):
        name = "Mobile"
        cv2.rectangle(img, (20,20),(210, 210),(255,0,0),2)
        cv2.putText(img, name, (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))
    else:
        name = "Pen"
        cv2.rectangle(img, (20,20),(210, 210),(255,0,0),2)
        cv2.putText(img, name, (20,20), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))

    cv2.imshow("Video", img)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

NameError: name 'pred' is not defined

In [ ]:
    for (x,y,w,h) in img:
        if (pred == [0]):
            name = "Mobile"
            cv2.rectangle(img, (x,y),(x+w, y+h),(255,0,0),2)
            cv2.putText(img, name, (x,y), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))
        else:
            name = "Pen"
            cv2.rectangle(img, (x,y),(x+w, y+h),(255,0,0),2)
            cv2.putText(img, name, (20,20), cv2.FONT_HERSHEY_COMPLEX, 0.5, (0, 0, 255))

In [22]:
import cv2
import numpy as np
classifier = cv2.CascadeClassifier(r'F:\MACHINE_LEARNING\CUSTOM_OBJECT_DETECTION\train\classifier/cascade.xml')
img = cv2.imread(r"F:\MACHINE_LEARNING\CUSTOM_OBJECT_DETECTION\train\p\1639935019368.jpg",cv2.IMREAD_UNCHANGED)
#scale_percent = 40
#width = int(img.shape[1] * scale_percent/100)
#height = int(img.shape[0] * scale_percent/100)
#dim = (width, height)
#img = cv2.resize(img,dim,interpolation=cv2.INTER_AREA)
img = cv2.resize(img,(32,32))
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img)
img = classifier.detectMultiScale(img, 1.5, 4)
print(img)
#if img is ():
 #   print("No objects found")

for (x,y,w,h) in img:
    cv2.rectangle(img, (x,y), (x+w,y+h), (127,0,255), 2)
    cv2.imshow('object Detection', img)
    cv2.waitKey(0)
    
cv2.destroyAllWindows()

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
()


In [14]:
import cv2
import numpy as np
classifier = cv2.CascadeClassifier(r'F:\MACHINE_LEARNING\CUSTOM_OBJECT_DETECTION\train\classifier/cascade.xml')
img = cv2.imread(r"F:\MACHINE_LEARNING\CUSTOM_OBJECT_DETECTION\train\p\1639935019368.jpg",cv2.IMREAD_UNCHANGED)
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
